name: recursive_reasoning.iect@IterativeErrorCorrectingTransformer
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

# Iteration config
max_iterations: 16
halt_exploration_prob: 0.1

# Larger architecture
num_layers: 6
hidden_size: 512
num_heads: 8
expansion: 4
num_pred_heads: 6

puzzle_emb_ndim: ${.hidden_size}
puzzle_emb_len: 8

forward_dtype: bfloat16
