name: recursive_reasoning.iect@IterativeErrorCorrectingTransformer
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

# Iteration config
max_iterations: 8
halt_exploration_prob: 0.1

# Architecture
num_layers: 2
hidden_size: 256
num_heads: 4
expansion: 4
num_pred_heads: 3

puzzle_emb_ndim: ${.hidden_size}
puzzle_emb_len: 8

forward_dtype: bfloat16
