name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

halt_exploration_prob: 0.1
halt_max_steps: 12  # Reduced from 16

H_cycles: 2  # Reduced from 3
L_cycles: 4  # Reduced from 6

H_layers: 0
L_layers: 2

hidden_size: 256  # Reduced from 512
num_heads: 4
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
forward_dtype: bfloat16

mlp_t: True  # MLP is faster than attention
puzzle_emb_len: 12
no_ACT_continue: True
