name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

halt_exploration_prob: 0.1
halt_max_steps: 14

H_cycles: 2
L_cycles: 6

H_layers: 0
L_layers: 4

hidden_size: 384
num_heads: 6
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
forward_dtype: bfloat16

mlp_t: True
puzzle_emb_len: 12
no_ACT_continue: True
